- name: Install PXE Components
  hosts: localhost
  become: true
  vars:
    version: 36
    pxe_main_IP: 192.168.1.250
  tasks:

    - name: Install HTTP
      ansible.builtin.dnf:
        name: httpd
        state: latest

    - name: Set Up Required Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /var/www/html/f{{ version }}-inst.local/images/pxeboot
        - /var/www/html/f{{ version }}-inst.local/ks
        - /var/www/html/f{{ version }}-inst.local/plays
        - /var/www/html/f{{ version }}-inst.local/other
        
    - name: Copy Required Files
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: ./plays, dest: "/var/www/html/f{{ version }}-inst.local/" }
        - { src: ./other, dest: "/var/www/html/f{{ version }}-inst.local/" }
      
    - name: Download Required Install Files
      ansible.builtin.get_url:
        url: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Everything/x86_64/os/images/pxeboot/vmlinuz", dest: "/var/www/html/f{{ version }}-inst.local/images/pxeboot/vmlinuz" }
        - { src: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Everything/x86_64/os/images/pxeboot/initrd.img", dest: "/var/www/html/f{{ version }}-inst.local/images/pxeboot/initrd.img" }
        - { src: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Everything/x86_64/os/images/install.img", dest: "/var/www/html/f{{ version }}-inst.local/images/install.img" }
        - { src: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Everything/x86_64/os/.treeinfo", dest: "/var/www/html/f{{ version }}-inst.local/.treeinfo" }
        - { src: "https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Everything/x86_64/os/.discinfo", dest: "/var/www/html/f{{ version }}-inst.local/.discinfo" }

    - name: Copy Template Files
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - { src: ./templates/kickstarts/basic-workstation.ks.j2, dest: "/var/www/html/f{{ version }}-inst.local/ks/fedora-{{ version }}-basic-workstation.ks" }
        - { src: ./templates/kickstarts/manual-install.ks.j2, dest: "/var/www/html/f{{ version }}-inst.local/ks/fedora-{{ version }}-manual-install.ks" }
        - { src: ./templates/kickstarts/virtual-workstation.ks.j2, dest: "/var/www/html/f{{ version }}-inst.local/ks/fedora-{{ version }}-virtual-workstation.ks" }

    - name: Remove Earlier Versions Repo
      ansible.builtin.file:
        path: "/var/www/html/f{{ version - 2 | int }}-inst.local"
        state: absent

    - name: Open Required Ports in Firewall
      ansible.builtin.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
        immediate: yes
      with_items:
        - http

    - name: Enable and Start Services
      ansible.builtin.systemd:
        name: "{{ item.name }}"
        state: "{{ item.state }}"
        enabled: yes
      with_items:
        - { name: httpd, state: started }

    - name: Write Local Install Repo File
      ansible.builtin.copy:
        dest: "/etc/yum.repos.d/f{{ version }}-inst.local.repo"
        content: |
          [f{{ version }}-inst.local]
          name=Fedora {{ version }} Local Install Repo
          baseurl=https://download.fedoraproject.org/pub/fedora/linux/releases/{{ version }}/Everything/x86_64/os/
          enabled=1
          gpgcheck=0

    - name: Sync Local Install Repo (this will take A WHILE)
      ansible.builtin.shell:
        cmd: "dnf reposync -a noarch -a x86_64 --delete --download-metadata --download-path /var/www/html/ --repoid f{{ version }}-inst.local"
  